/**
 * i18n.ts: every user-facing string, in English and Bahasa Indonesia.
 *
 * Rules (CLAUDE.md): both languages always; Indonesian reads as everyday
 * Indonesian ("Akun" for account); no em dash anywhere; a missing value prints
 * "-". Web pages get both languages as a static bundle
 * (public/app/static/js/i18n-all.js, generated by scripts/build_i18n.ts);
 * Telegram and server-rendered reports call t() here.
 *
 * Error keys are `err.<code>`, one per code an action or the engine can
 * return. tests/unit/i18n.test.ts fails when a code has no string.
 */

export const DEFAULT_LANG = "en";
export const SUPPORTED_LANGS = ["en", "id"] as const;
export type Lang = (typeof SUPPORTED_LANGS)[number];

export function normalizeLang(lang: string | null | undefined): Lang {
  const code = String(lang ?? "").trim().toLowerCase().slice(0, 2);
  return code === "id" ? "id" : "en";
}

interface Entry {
  en: string;
  id: string;
}

export const STRINGS: Record<string, Entry> = {
  // ── app ──
  "app.name": { en: "Split Bill", id: "Split Bill" },
  "app.tagline": { en: "Split bills with friends and on trips", id: "Bagi tagihan bareng teman dan saat liburan" },
  "landing.pitch": {
    en: "One bill or a whole trip. By item, evenly or by percent, in any currency. Every cent adds up.",
    id: "Satu tagihan atau satu perjalanan penuh. Per item, rata, atau persen, dalam mata uang apa pun. Setiap sen tercatat pas.",
  },

  // ── common ──
  "common.save": { en: "Save", id: "Simpan" },
  "common.saved": { en: "Saved.", id: "Tersimpan." },
  "common.add": { en: "Add", id: "Tambah" },
  "common.edit": { en: "Edit", id: "Ubah" },
  "common.delete": { en: "Delete", id: "Hapus" },
  "common.remove": { en: "Remove", id: "Buang" },
  "common.close": { en: "Close", id: "Tutup" },
  "common.back": { en: "Back", id: "Kembali" },
  "common.cancel": { en: "Cancel", id: "Batal" },
  "common.copy": { en: "Copy", id: "Salin" },
  "common.copied": { en: "Copied.", id: "Tersalin." },
  "common.all": { en: "All", id: "Semua" },
  "common.actions": { en: "Actions", id: "Tindakan" },
  "confirm.title": { en: "Are you sure?", id: "Yakin?" },
  "confirm.proceed": { en: "Continue", id: "Lanjutkan" },

  // ── nav ──
  "nav.splits": { en: "My splits", id: "Patunganku" },
  "nav.settings": { en: "Settings", id: "Pengaturan" },
  "nav.signout": { en: "Sign out", id: "Keluar" },

  // ── auth ──
  "auth.back_home": { en: "Back to home", id: "Kembali ke beranda" },
  "auth.identifier": { en: "Username or email", id: "Nama pengguna atau email" },
  "auth.password": { en: "Password", id: "Kata sandi" },
  "auth.password_rule": { en: "At least 8 characters with one symbol.", id: "Minimal 8 karakter dengan satu simbol." },
  "auth.remember": { en: "Remember me", id: "Ingat saya" },
  "auth.signin": { en: "Sign In", id: "Masuk" },
  "auth.google": { en: "Sign in with Google", id: "Masuk dengan Google" },
  "auth.no_account": { en: "No account yet?", id: "Belum punya akun?" },
  "auth.create": { en: "Create one", id: "Buat akun" },
  "auth.create_title": { en: "Create account", id: "Buat akun" },
  "auth.create_btn": { en: "Create Account", id: "Buat Akun" },
  "auth.have_account": { en: "Already have an account?", id: "Sudah punya akun?" },
  "auth.display_name": { en: "Your name", id: "Namamu" },
  "auth.username": { en: "Username", id: "Nama pengguna" },
  "auth.email": { en: "Email", id: "Email" },
  "verify.title": { en: "Confirm your email", id: "Konfirmasi emailmu" },
  "verify.desc": { en: "We sent a 6-digit code to {0}.", id: "Kami mengirim kode 6 angka ke {0}." },
  "verify.code": { en: "Code", id: "Kode" },
  "verify.confirm": { en: "Confirm", id: "Konfirmasi" },
  "verify.resend": { en: "Send Again", id: "Kirim Ulang" },
  "verify.sent": { en: "New code sent.", id: "Kode baru terkirim." },
  "verify.done": { en: "Email confirmed.", id: "Email terkonfirmasi." },

  // ── home ──
  "home.title": { en: "My splits", id: "Patunganku" },
  "home.splits": { en: "Splits", id: "Patungan" },
  "home.new_oneoff": { en: "New One-off", id: "Patungan Baru" },
  "home.new_trip": { en: "New Trip", id: "Perjalanan Baru" },
  "home.col_name": { en: "Name", id: "Nama" },
  "home.col_spent": { en: "Spent", id: "Total" },
  "home.col_mine": { en: "My balance", id: "Saldoku" },
  "home.empty": { en: "No splits yet.", id: "Belum ada patungan." },
  "kind.one_off": { en: "One-off", id: "Sekali bayar" },
  "kind.travel": { en: "Trip", id: "Perjalanan" },
  "status.open": { en: "Open", id: "Berjalan" },
  "status.not_settled": { en: "Not settled", id: "Belum diselesaikan" },
  "status.settled": { en: "Settled", id: "Selesai" },
  "offline.banner": { en: "Offline. Showing what you saw on {0}. Changes need a connection.", id: "Sedang luring. Menampilkan data terakhir dari {0}. Perubahan butuh koneksi." },

  // ── new split ──
  "new.name": { en: "Name", id: "Nama" },
  "new.currency": { en: "Currency", id: "Mata uang" },
  "new.settle_currency": { en: "Settle in", id: "Diselesaikan dalam" },
  "new.people": { en: "People", id: "Orang" },
  "new.people_tip": {
    en: "Type a name for someone without the app, or @username for an app user.",
    id: "Ketik nama untuk orang yang tidak memakai aplikasi, atau @namapengguna untuk pengguna aplikasi.",
  },
  "new.person_ph": { en: "Name or @username", id: "Nama atau @namapengguna" },
  "new.create": { en: "Create", id: "Buat" },

  // ── group ──
  "grp.manage": { en: "Manage", id: "Kelola" },
  "grp.rename": { en: "Rename", id: "Ganti Nama" },
  "grp.change_currency": { en: "Change Currency", id: "Ganti Mata Uang" },
  "grp.delete": { en: "Delete Split", id: "Hapus Patungan" },
  "grp.delete_confirm": { en: "Delete \"{0}\" for everyone?", id: "Hapus \"{0}\" untuk semua anggota?" },
  "grp.settle": { en: "Settle", id: "Selesaikan" },
  "grp.settle_confirm": {
    en: "Lock these numbers as the final settlement? No bills can be added until you reopen.",
    id: "Kunci angka ini sebagai penyelesaian akhir? Tagihan baru tidak bisa ditambah sampai dibuka lagi.",
  },
  "grp.settled_toast": { en: "Settled.", id: "Selesai." },
  "grp.reopen": { en: "Reopen", id: "Buka Lagi" },
  "grp.reopen_confirm": {
    en: "Reopen to add or fix bills? Paid transfers stay recorded.",
    id: "Buka lagi untuk menambah atau memperbaiki tagihan? Transfer yang sudah dibayar tetap tercatat.",
  },
  "grp.reopened_toast": { en: "Reopened.", id: "Dibuka lagi." },

  // ── balances ──
  "bal.title": { en: "Balances", id: "Saldo" },
  "bal.member": { en: "Member", id: "Anggota" },
  "bal.paid": { en: "Paid", id: "Membayar" },
  "bal.share": { en: "Share", id: "Bagian" },
  "bal.net": { en: "Balance", id: "Saldo" },
  "bal.net_tip": { en: "Plus: gets money back. Minus: owes money.", id: "Plus: menerima uang kembali. Minus: berutang." },
  "bal.spent": { en: "Total spent", id: "Total belanja" },
  "bal.mine": { en: "My balance", id: "Saldoku" },
  "bal.you_get": { en: "You get back", id: "Kamu terima" },
  "bal.you_owe": { en: "You owe", id: "Kamu berutang" },
  "bal.even": { en: "Even", id: "Impas" },
  "bal.transfers": { en: "Who pays whom", id: "Siapa bayar siapa" },
  "bal.transfers_tip": { en: "The fewest payments that settle everyone.", id: "Jumlah transfer paling sedikit agar semua impas." },
  "bal.all_even": { en: "Everyone is even.", id: "Semua sudah impas." },
  "bal.no_bills": { en: "No bills yet.", id: "Belum ada tagihan." },
  "xfer.mark_paid": { en: "Mark Paid", id: "Tandai Lunas" },
  "xfer.paid": { en: "Paid", id: "Lunas" },
  "xfer.undo": { en: "Undo", id: "Batalkan" },
  "xfer.paid_toast": { en: "Marked as paid.", id: "Ditandai lunas." },

  // ── bills ──
  "bill.title_list": { en: "Bills", id: "Tagihan" },
  "bill.add": { en: "Add Bill", id: "Tambah Tagihan" },
  "bill.edit": { en: "Edit Bill", id: "Ubah Tagihan" },
  "bill.view": { en: "Bill", id: "Tagihan" },
  "bill.col_what": { en: "Bill", id: "Tagihan" },
  "bill.col_payer": { en: "Paid by", id: "Dibayar oleh" },
  "bill.paid_by_x": { en: "paid by {0}", id: "dibayar {0}" },
  "bill.col_total": { en: "Total", id: "Total" },
  "bill.col_mine": { en: "My share", id: "Bagianku" },
  "bill.empty": { en: "No bills yet.", id: "Belum ada tagihan." },
  "bill.desc": { en: "What for", id: "Untuk apa" },
  "bill.date": { en: "Date", id: "Tanggal" },
  "bill.currency": { en: "Currency", id: "Mata uang" },
  "bill.payer": { en: "Paid by", id: "Dibayar oleh" },
  "bill.item": { en: "Item", id: "Item" },
  "bill.item_ph": { en: "Item", id: "Nama item" },
  "bill.amount": { en: "Amount", id: "Jumlah" },
  "bill.add_item": { en: "Add Item", id: "Tambah Item" },
  "bill.stated": { en: "Receipt total", id: "Total di struk" },
  "bill.stated_tip": {
    en: "Optional. When filled, the bill cannot be saved until the lines add up to it.",
    id: "Opsional. Jika diisi, tagihan baru bisa disimpan setelah semua baris pas dengan total ini.",
  },
  "bill.total": { en: "Total", id: "Total" },
  "bill.for_whom": { en: "For whom", id: "Untuk siapa" },
  "bill.fill_rest": { en: "Fill the rest", id: "Isi sisanya" },
  "bill.lines_total": { en: "Lines:", id: "Baris:" },
  "bill.matches": { en: "Matches the receipt", id: "Sesuai struk" },
  "bill.diff": { en: "Off by", id: "Selisih" },
  "bill.add_diff": { en: "Add as Other", id: "Tambah sebagai Lainnya" },
  "bill.pct_total": { en: "Total percent", id: "Total persen" },
  "bill.shares": { en: "Shares", id: "Bagian" },
  "bill.paid_chip": { en: "paid", id: "membayar" },
  "bill.converted": { en: "Total {0} at {1}", id: "Total {0} dengan kurs {1}" },
  "bill.saved": { en: "Bill saved.", id: "Tagihan tersimpan." },
  "bill.deleted": { en: "Bill deleted.", id: "Tagihan dihapus." },
  "bill.delete_confirm": { en: "Delete this bill?", id: "Hapus tagihan ini?" },
  "mode.items": { en: "By item", id: "Per item" },
  "mode.even": { en: "Evenly", id: "Rata" },
  "mode.percent": { en: "By percent", id: "Per persen" },
  "adj.kind": { en: "Kind", id: "Jenis" },
  "adj.tax": { en: "Tax", id: "Pajak" },
  "adj.service": { en: "Service", id: "Servis" },
  "adj.tip": { en: "Tip", id: "Tip" },
  "adj.discount": { en: "Discount", id: "Diskon" },
  "adj.other": { en: "Other", id: "Lainnya" },

  // ── input modes ──
  "input.form": { en: "Form", id: "Formulir" },
  "input.chat": { en: "Chat", id: "Obrolan" },
  "input.photo": { en: "Photo", id: "Foto" },
  "input.chat_label": { en: "Describe the bill", id: "Ceritakan tagihannya" },
  "input.chat_ph": { en: "Lunch 60 paid by Ali, split evenly with Bob and Cal", id: "Makan siang 60 ribu dibayar Ali, bagi rata dengan Bob dan Cal" },
  "input.photo_pick": { en: "Take or choose a receipt photo", id: "Ambil atau pilih foto struk" },
  "input.caption": { en: "Note (optional)", id: "Catatan (opsional)" },
  "input.caption_ph": { en: "Paid by Ali, drinks for Bob", id: "Dibayar Ali, minuman untuk Bob" },
  "input.read": { en: "Read", id: "Baca" },
  "input.reading": { en: "Reading...", id: "Membaca..." },
  "input.read_done": { en: "Check the form, then save.", id: "Periksa formulir, lalu simpan." },
  "input.unknown": { en: "Not in this split: {0}. Add them under Members or pick someone else.", id: "Tidak ada di tagihan ini: {0}. Tambahkan di Anggota atau pilih orang lain." },

  // ── payments ──
  "pay.title_list": { en: "Payments", id: "Pembayaran" },
  "pay.tip": { en: "Money already handed back, for example cash during the trip.", id: "Uang yang sudah dikembalikan, misalnya tunai selama perjalanan." },
  "pay.add": { en: "Record Payment", id: "Catat Pembayaran" },
  "pay.col_who": { en: "From, to", id: "Dari, ke" },
  "pay.col_amount": { en: "Amount", id: "Jumlah" },
  "pay.from": { en: "From", id: "Dari" },
  "pay.to": { en: "To", id: "Ke" },
  "pay.note": { en: "Note", id: "Catatan" },
  "pay.empty": { en: "No payments yet.", id: "Belum ada pembayaran." },
  "pay.saved": { en: "Payment recorded.", id: "Pembayaran tercatat." },
  "pay.deleted": { en: "Payment deleted.", id: "Pembayaran dihapus." },
  "pay.delete_confirm": { en: "Delete this payment?", id: "Hapus pembayaran ini?" },
  "pay.from_settle": { en: "settlement", id: "penyelesaian" },

  // ── members ──
  "mem.title": { en: "Members", id: "Anggota" },
  "mem.add": { en: "Add Member", id: "Tambah Anggota" },
  "mem.name": { en: "Name", id: "Nama" },
  "mem.you": { en: "you", id: "kamu" },
  "mem.owner": { en: "Owner", id: "Pemilik" },
  "mem.no_app": { en: "No app", id: "Tanpa aplikasi" },
  "mem.inactive": { en: "Inactive", id: "Nonaktif" },
  "mem.rename": { en: "Rename", id: "Ganti Nama" },
  "mem.remove": { en: "Remove", id: "Keluarkan" },
  "mem.remove_confirm": { en: "Remove {0} from this split?", id: "Keluarkan {0} dari patungan ini?" },
  "mem.removed": { en: "Removed.", id: "Dikeluarkan." },
  "mem.deactivated": { en: "Has history, so marked inactive instead.", id: "Punya riwayat, jadi ditandai nonaktif." },
  "mem.reactivate": { en: "Reactivate", id: "Aktifkan Lagi" },
  "mem.link": { en: "Link to App User", id: "Hubungkan ke Pengguna" },
  "mem.link_to": { en: "Who is this?", id: "Siapa orang ini?" },
  "mem.link_none": { en: "Nobody new has joined yet.", id: "Belum ada anggota baru yang bergabung." },
  "mem.linked": { en: "Linked. Their history moved over.", id: "Terhubung. Riwayatnya sudah dipindahkan." },
  "mem.invite": { en: "Invite link", id: "Tautan undangan" },
  "mem.invite_tip": { en: "Anyone with this link can join with their own account.", id: "Siapa pun yang punya tautan ini bisa bergabung dengan akunnya sendiri." },
  "mem.invite_reset": { en: "New Link", id: "Tautan Baru" },
  "mem.invite_reset_confirm": { en: "Make a new link? The old one stops working.", id: "Buat tautan baru? Tautan lama tidak berlaku lagi." },
  "join.subtitle": { en: "You are invited to this trip", id: "Kamu diundang ke perjalanan ini" },
  "join.button": { en: "Join Trip", id: "Gabung" },

  // ── rates ──
  "rate.title": { en: "Rates", id: "Kurs" },
  "rate.tip": {
    en: "One rate per currency per day, for the whole group. A bill uses the latest rate on or before its date.",
    id: "Satu kurs per mata uang per hari, untuk seluruh grup. Tagihan memakai kurs terbaru pada atau sebelum tanggalnya.",
  },
  "rate.add": { en: "Add Rate", id: "Tambah Kurs" },
  "rate.edit": { en: "Edit Rate", id: "Ubah Kurs" },
  "rate.col_from": { en: "From", id: "Mulai" },
  "rate.col_rate": { en: "Rate", id: "Kurs" },
  "rate.from_start": { en: "From the start", id: "Sejak awal" },
  "rate.flip": { en: "Flip", id: "Balik" },
  "rate.auto": { en: "Auto", id: "Otomatis" },
  "rate.auto_done": { en: "Market rate filled in. Check it, then save.", id: "Kurs pasar sudah diisi. Periksa, lalu simpan." },
  "rate.empty": { en: "No rates yet.", id: "Belum ada kurs." },
  "rate.deleted": { en: "Rate deleted.", id: "Kurs dihapus." },
  "rate.saved": { en: "Rate saved.", id: "Kurs tersimpan." },
  "rate.delete_confirm": { en: "Delete this rate?", id: "Hapus kurs ini?" },
  "rate.missing_banner": { en: "No {0} rate for {1}. The owner adds it under Rates before settling.", id: "Belum ada kurs {0} untuk {1}. Pemilik menambahkannya di Kurs sebelum penyelesaian." },
  "rate.missing_for": { en: "No {0} rate for {1} yet. The owner adds it under Rates.", id: "Belum ada kurs {0} untuk {1}. Pemilik menambahkannya di Kurs." },

  // ── reports ──
  "rpt.button": { en: "Report", id: "Laporan" },
  "rpt.group": { en: "Group", id: "Grup" },
  "rpt.individual": { en: "Individual", id: "Perorangan" },
  "rpt.not_settled": { en: "NOT SETTLED", id: "BELUM DISELESAIKAN" },
  "rpt.settled_on": { en: "SETTLED {0}", id: "DISELESAIKAN {0}" },
  "rpt.as_of": { en: "as of {0}", id: "per {0}" },
  "rpt.group_title": { en: "Group report", id: "Laporan grup" },
  "rpt.member_title": { en: "Report for {0}", id: "Laporan untuk {0}" },
  "rpt.currency": { en: "Currency: {0}", id: "Mata uang: {0}" },
  "rpt.spent": { en: "Total spent: {0}", id: "Total belanja: {0}" },
  "rpt.balances": { en: "Balances", id: "Saldo" },
  "rpt.transfers": { en: "Who pays whom", id: "Siapa bayar siapa" },
  "rpt.none": { en: "Everyone is even.", id: "Semua sudah impas." },
  "rpt.paid_tag": { en: "(paid)", id: "(lunas)" },
  "rpt.rates": { en: "Rates used", id: "Kurs yang dipakai" },
  "rpt.you_pay": { en: "You pay", id: "Kamu bayar" },
  "rpt.you_get": { en: "You receive", id: "Kamu terima" },
  "rpt.net": { en: "Balance: {0}", id: "Saldo: {0}" },
  "rpt.paid_total": { en: "Paid for the group: {0}", id: "Dibayarkan untuk grup: {0}" },
  "rpt.share_total": { en: "Your share: {0}", id: "Bagianmu: {0}" },
  "rpt.bills": { en: "Bills", id: "Tagihan" },
  "rpt.paid_by": { en: "paid by {0}", id: "dibayar {0}" },
  "rpt.your_share": { en: "your share", id: "bagianmu" },
  "rpt.payments": { en: "Payments", id: "Pembayaran" },
  "rpt.rounding": { en: "Rounding", id: "Pembulatan" },
  "rpt.col_member": { en: "Member", id: "Anggota" },
  "rpt.col_paid": { en: "Paid", id: "Membayar" },
  "rpt.col_share": { en: "Share", id: "Bagian" },
  "rpt.col_net": { en: "Balance", id: "Saldo" },
  "rpt.footer": { en: "Made with Split Bill", id: "Dibuat dengan Split Bill" },
  "rpt.downloading": { en: "Preparing file...", id: "Menyiapkan berkas..." },

  // ── settings ──
  "set.profile": { en: "Profile", id: "Profil" },
  "set.language": { en: "Language", id: "Bahasa" },
  "set.currency": { en: "Default currency", id: "Mata uang utama" },
  "set.timezone": { en: "Time zone", id: "Zona waktu" },
  "set.password": { en: "Password", id: "Kata sandi" },
  "set.pw_current": { en: "Current password", id: "Kata sandi sekarang" },
  "set.pw_new": { en: "New password", id: "Kata sandi baru" },
  "set.pw_change": { en: "Change Password", id: "Ganti Kata Sandi" },
  "set.pw_changed": { en: "Password changed.", id: "Kata sandi diganti." },
  "set.account": { en: "Account", id: "Akun" },

  // ── telegram (web side) ──
  "tg.title": { en: "Telegram", id: "Telegram" },
  "tg.link": { en: "Connect Telegram", id: "Hubungkan Telegram" },
  "tg.relink": { en: "Connect Again", id: "Hubungkan Ulang" },
  "tg.linked": { en: "Connected. Send bills and receipt photos to the bot.", id: "Terhubung. Kirim tagihan dan foto struk ke bot." },
  "tg.web_not_linked": { en: "Add bills by chat or receipt photo from Telegram.", id: "Tambah tagihan lewat obrolan atau foto struk dari Telegram." },
  "tg.open_hint": { en: "Press Start in Telegram to finish.", id: "Tekan Start di Telegram untuk menyelesaikan." },


  // ── Telegram bot ──
  "tg.help_private": {
    en: "Send me a bill as text, like \"Lunch 60k paid by Ali, split evenly\", or a receipt photo. I fill a draft you save with one tap.\n\n/groups pick the split to add to\n/report group report\n/me your report",
    id: "Kirim tagihan sebagai teks, misalnya \"Makan siang 60rb dibayar Ali, bagi rata\", atau foto struk. Aku siapkan drafnya, kamu simpan dengan sekali ketuk.\n\n/groups pilih patungan tujuan\n/report laporan grup\n/me laporanmu",
  },
  "tg.help_group": {
    en: "/bill lunch 60k paid by Ali split all: add a bill\n/bill alone, then reply with a receipt photo\n/report group report\n/me your report, sent privately",
    id: "/bill makan 60rb dibayar Ali bagi rata: tambah tagihan\n/bill saja, lalu balas dengan foto struk\n/report laporan grup\n/me laporanmu, dikirim pribadi",
  },
  "tg.not_linked": {
    en: "This Telegram account is not connected yet. Open Split Bill, go to Settings, tap Connect Telegram.",
    id: "Akun Telegram ini belum terhubung. Buka Split Bill, masuk ke Pengaturan, ketuk Hubungkan Telegram.",
  },
  "tg.linked_ok": { en: "Connected as {0}. Send a bill or a receipt photo.", id: "Terhubung sebagai {0}. Kirim tagihan atau foto struk." },
  "tg.unlinked": { en: "Disconnected.", id: "Terputus." },
  "tg.pick_group": { en: "Which split should bills go to?", id: "Tagihan dikirim ke patungan mana?" },
  "tg.no_groups": { en: "You have no open splits. Create one in the app first.", id: "Belum ada patungan yang berjalan. Buat dulu di aplikasi." },
  "tg.group_set": { en: "Bills now go to {0}.", id: "Tagihan sekarang masuk ke {0}." },
  "tg.chat_not_bound": {
    en: "This chat is not connected to a trip. The trip owner connects it in Split Bill: open the trip, Manage, Connect Telegram Group.",
    id: "Obrolan ini belum terhubung ke perjalanan. Pemilik perjalanan menghubungkannya di Split Bill: buka perjalanan, Kelola, Hubungkan Grup Telegram.",
  },
  "tg.bound": { en: "This chat now adds bills to {0}.", id: "Obrolan ini sekarang menambah tagihan ke {0}." },
  "tg.unbound": { en: "This chat is no longer connected.", id: "Obrolan ini tidak terhubung lagi." },
  "tg.link_first": { en: "{0}, connect your account first: open @{1} privately and follow the steps.", id: "{0}, hubungkan akunmu dulu: buka @{1} secara pribadi dan ikuti langkahnya." },
  "tg.send_bill": { en: "Reply to this message with the bill as text or a receipt photo.", id: "Balas pesan ini dengan tagihan berupa teks atau foto struk." },
  "tg.reading": { en: "Reading...", id: "Membaca..." },
  "tg.draft_title": { en: "Draft", id: "Draf" },
  "tg.paid_by": { en: "Paid by {0}", id: "Dibayar {0}" },
  "tg.draft_fix": { en: "Not ready to save: {0}", id: "Belum bisa disimpan: {0}" },
  "tg.btn_save": { en: "Save", id: "Simpan" },
  "tg.btn_edit": { en: "Edit in app", id: "Ubah di aplikasi" },
  "tg.btn_cancel": { en: "Cancel", id: "Batal" },
  "tg.saved": { en: "Saved.", id: "Tersimpan." },
  "tg.cancelled": { en: "Cancelled.", id: "Dibatalkan." },
  "tg.not_yours": { en: "Only whoever sent this can use these buttons.", id: "Hanya pengirimnya yang bisa memakai tombol ini." },
  "tg.sent_private": { en: "Sent to you privately.", id: "Sudah dikirim ke pesan pribadimu." },
  "tg.start_private": { en: "Open @{0} and press Start first, then try again.", id: "Buka @{0} dan tekan Start dulu, lalu coba lagi." },
  "tg.album_first": { en: "Only the first photo is read. Send receipts one at a time.", id: "Hanya foto pertama yang dibaca. Kirim struk satu per satu." },
  "tg.file_failed": { en: "Could not get that photo from Telegram. Try again.", id: "Foto tidak bisa diambil dari Telegram. Coba lagi." },
  "tg.unknown_cmd": { en: "Unknown command. Send /help.", id: "Perintah tidak dikenal. Kirim /help." },
  "tg.bind_btn": { en: "Connect Telegram Group", id: "Hubungkan Grup Telegram" },
  "tg.bind_hint": { en: "Pick the Telegram group in the window that opens.", id: "Pilih grup Telegram di jendela yang terbuka." },

  // ── errors (err.<code>) ──
  "err.generic": { en: "Something went wrong. Try again.", id: "Terjadi kesalahan. Coba lagi." },
  "err.internal": { en: "Something went wrong on our side. Nothing was saved.", id: "Terjadi kesalahan di sisi kami. Tidak ada yang tersimpan." },
  "err.network": { en: "Could not reach the server. Check your connection.", id: "Tidak bisa terhubung ke server. Periksa koneksimu." },
  "err.offline": { en: "You are offline. This needs a connection.", id: "Kamu sedang luring. Ini butuh koneksi." },
  "err.login_failed": { en: "Wrong username, email or password.", id: "Nama pengguna, email, atau kata sandi salah." },
  "err.login_required": { en: "Please sign in.", id: "Silakan masuk." },
  "err.username_invalid": { en: "Username: 3 to 32 letters, numbers or _.", id: "Nama pengguna: 3 sampai 32 huruf, angka, atau _." },
  "err.username_taken": { en: "That username is taken.", id: "Nama pengguna itu sudah dipakai." },
  "err.email_invalid": { en: "Enter a valid email.", id: "Masukkan email yang valid." },
  "err.email_taken": { en: "That email already has an account.", id: "Email itu sudah punya akun." },
  "err.password_short": { en: "Password needs at least 8 characters.", id: "Kata sandi minimal 8 karakter." },
  "err.password_long": { en: "Password is too long.", id: "Kata sandi terlalu panjang." },
  "err.password_special": { en: "Password needs at least one symbol.", id: "Kata sandi perlu minimal satu simbol." },
  "err.password_wrong": { en: "Current password is wrong.", id: "Kata sandi sekarang salah." },
  "err.code_invalid": { en: "That code is not right.", id: "Kode itu tidak tepat." },
  "err.code_expired": { en: "That code expired. Send a new one.", id: "Kode sudah kedaluwarsa. Kirim yang baru." },
  "err.code_locked": { en: "Too many tries. Send a new code.", id: "Terlalu banyak percobaan. Kirim kode baru." },
  "err.code_wait": { en: "Wait a minute before sending another code.", id: "Tunggu satu menit sebelum mengirim kode lagi." },
  "err.name_required": { en: "Enter a name.", id: "Masukkan nama." },
  "err.timezone_invalid": { en: "Unknown time zone.", id: "Zona waktu tidak dikenal." },
  "err.currency_invalid": { en: "Pick a currency from the list.", id: "Pilih mata uang dari daftar." },
  "err.currency_locked": { en: "The currency cannot change once payments exist.", id: "Mata uang tidak bisa diganti setelah ada pembayaran." },
  "err.kind_invalid": { en: "Not possible for this kind of split.", id: "Tidak bisa untuk jenis patungan ini." },
  "err.group_not_found": { en: "This split does not exist or you are not in it.", id: "Patungan ini tidak ada atau kamu bukan anggotanya." },
  "err.group_settled": { en: "This split is settled. The owner can reopen it.", id: "Patungan ini sudah selesai. Pemilik bisa membukanya lagi." },
  "err.group_open": { en: "This split is not settled yet.", id: "Patungan ini belum diselesaikan." },
  "err.forbidden": { en: "Not allowed.", id: "Tidak diizinkan." },
  "err.not_found": { en: "Not found.", id: "Tidak ditemukan." },
  "err.unsupported": { en: "Unsupported request.", id: "Permintaan tidak didukung." },
  "err.owner_only": { en: "Only the owner can do this.", id: "Hanya pemilik yang bisa melakukan ini." },
  "err.owner_cannot_leave": { en: "The owner cannot be removed.", id: "Pemilik tidak bisa dikeluarkan." },
  "err.stale_revision": { en: "Someone changed this split. Check the new numbers and try again.", id: "Ada yang mengubah patungan ini. Periksa angka terbaru lalu coba lagi." },
  "err.stale_version": { en: "Someone edited this bill. Reopen it to see the latest.", id: "Ada yang mengubah tagihan ini. Buka lagi untuk melihat versi terbaru." },
  "err.settle_incomplete": { en: "Add the missing rates before settling.", id: "Tambahkan kurs yang kurang sebelum penyelesaian." },
  "err.invite_invalid": { en: "This invite link no longer works.", id: "Tautan undangan ini sudah tidak berlaku." },
  "err.user_not_found": { en: "No app user @{username}.", id: "Tidak ada pengguna @{username}." },
  "err.member_already": { en: "Already a member.", id: "Sudah menjadi anggota." },
  "err.member_unknown": { en: "Someone on this bill is not in this split.", id: "Ada orang di tagihan ini yang bukan anggota." },
  "err.member_name_taken": { en: "Two members cannot share a name.", id: "Dua anggota tidak boleh bernama sama." },
  "err.member_inactive": { en: "You are inactive in this split.", id: "Kamu nonaktif di patungan ini." },
  "err.member_inactive_pick": { en: "{name} is inactive. Reactivate them first.", id: "{name} nonaktif. Aktifkan dulu." },
  "err.link_not_dummy": { en: "Only a member without the app can be linked.", id: "Hanya anggota tanpa aplikasi yang bisa dihubungkan." },
  "err.link_target_invalid": { en: "Pick a member who joined with the app.", id: "Pilih anggota yang bergabung lewat aplikasi." },
  "err.link_target_has_history": {
    en: "That person already has bills in this split under their own name, so the two cannot be joined.",
    id: "Orang itu sudah punya tagihan atas namanya sendiri di sini, jadi keduanya tidak bisa digabung.",
  },
  "err.bill_not_found": { en: "That bill no longer exists.", id: "Tagihan itu sudah tidak ada." },
  "err.bill_edit_forbidden": { en: "Only whoever added this bill, or the owner, can change it.", id: "Hanya yang menambahkan tagihan ini, atau pemilik, yang bisa mengubahnya." },
  "err.bill_too_big": { en: "Too many lines on one bill.", id: "Terlalu banyak baris dalam satu tagihan." },
  "err.bill_invalid": { en: "This bill is incomplete.", id: "Tagihan ini belum lengkap." },
  "err.description_required": { en: "Say what the bill is for.", id: "Isi untuk apa tagihan ini." },
  "err.date_invalid": { en: "Enter a valid date.", id: "Masukkan tanggal yang valid." },
  "err.date_future": { en: "The date is in the future.", id: "Tanggalnya di masa depan." },
  "err.qty_invalid": { en: "Enter a valid quantity.", id: "Masukkan jumlah barang yang valid." },
  "err.mode_invalid": { en: "Pick how to split.", id: "Pilih cara membagi." },
  "err.payer_unknown": { en: "Pick who paid.", id: "Pilih siapa yang membayar." },
  "err.amount_invalid": { en: "That amount is not a number.", id: "Jumlah itu bukan angka." },
  "err.amount_too_precise": { en: "Too many decimals for this currency.", id: "Terlalu banyak desimal untuk mata uang ini." },
  "err.amount_too_large": { en: "That amount is too large.", id: "Jumlah itu terlalu besar." },
  "err.amount_zero": { en: "Enter an amount above zero.", id: "Masukkan jumlah di atas nol." },
  "err.amount_negative": { en: "Amounts cannot be negative here.", id: "Jumlah tidak boleh negatif di sini." },
  "err.total_invalid": { en: "Enter the total.", id: "Masukkan totalnya." },
  "err.total_not_positive": { en: "The total must be above zero.", id: "Totalnya harus di atas nol." },
  "err.total_mismatch": { en: "The total does not match the lines.", id: "Total tidak sama dengan jumlah baris." },
  "err.stated_total_mismatch": { en: "The lines do not add up to the receipt total.", id: "Jumlah baris tidak sama dengan total struk." },
  "err.items_empty": { en: "Add at least one item.", id: "Tambahkan minimal satu item." },
  "err.item_invalid": { en: "Item {index} is not valid.", id: "Item {index} tidak valid." },
  "err.item_negative": { en: "Item {index} cannot be negative. Use Discount.", id: "Item {index} tidak boleh negatif. Pakai Diskon." },
  "err.item_unassigned": { en: "Item {index} has nobody on it.", id: "Item {index} belum ada orangnya." },
  "err.item_duplicate_member": { en: "Someone appears twice on item {index}.", id: "Ada orang yang muncul dua kali di item {index}." },
  "err.items_subtotal_zero": { en: "Give the items a price, or split evenly.", id: "Beri harga pada item, atau bagi rata." },
  "err.adjustment_invalid": { en: "A tax, service or discount line is not valid.", id: "Baris pajak, servis, atau diskon tidak valid." },
  "err.adjustment_zero": { en: "Remove empty tax, service or discount lines.", id: "Hapus baris pajak, servis, atau diskon yang kosong." },
  "err.adjustment_sign": { en: "Enter tax, service and discount as positive amounts.", id: "Isi pajak, servis, dan diskon dengan angka positif." },
  "err.adjustments_not_allowed": { en: "Tax and discount only apply when splitting by item.", id: "Pajak dan diskon hanya berlaku untuk pembagian per item." },
  "err.participants_empty": { en: "Pick who shares this bill.", id: "Pilih siapa yang ikut menanggung tagihan ini." },
  "err.participants_not_allowed": { en: "This split mode does not take a list of people.", id: "Mode ini tidak memakai daftar orang." },
  "err.participant_duplicate": { en: "{member} is listed twice.", id: "{member} tercantum dua kali." },
  "err.percent_invalid": { en: "Each percent must be between 0.01 and 100.", id: "Setiap persen harus antara 0,01 dan 100." },
  "err.percent_too_precise": { en: "Use at most 2 decimals for percents.", id: "Pakai maksimal 2 desimal untuk persen." },
  "err.percent_sum": { en: "Percents must add up to exactly 100.", id: "Total persen harus tepat 100." },
  "err.rate_invalid": { en: "Enter a rate above zero.", id: "Masukkan kurs di atas nol." },
  "err.rate_too_precise": { en: "Use at most 12 decimals for a rate.", id: "Pakai maksimal 12 desimal untuk kurs." },
  "err.rate_too_large": { en: "That rate is too large. Try Flip.", id: "Kurs itu terlalu besar. Coba Balik." },
  "err.rate_missing": { en: "No {currency} rate for {date}. The owner adds it under Rates.", id: "Belum ada kurs {currency} untuk {date}. Pemilik menambahkannya di Kurs." },
  "err.rate_not_allowed": { en: "The settlement currency needs no rate.", id: "Mata uang penyelesaian tidak butuh kurs." },
  "err.rate_needed": { en: "A bill still uses this rate. Change or delete that bill first.", id: "Masih ada tagihan yang memakai kurs ini. Ubah atau hapus tagihan itu dulu." },
  "err.rate_not_found": { en: "That rate no longer exists.", id: "Kurs itu sudah tidak ada." },
  "err.rate_unavailable": { en: "No market rate available. Enter it yourself.", id: "Kurs pasar tidak tersedia. Isi sendiri." },
  "err.convert_zero": { en: "Too small to convert into the settlement currency.", id: "Terlalu kecil untuk dikonversi ke mata uang penyelesaian." },
  "err.payment_self": { en: "Pick two different people.", id: "Pilih dua orang yang berbeda." },
  "err.payment_forbidden": { en: "Only whoever received the money, or the owner, can record this.", id: "Hanya penerima uang, atau pemilik, yang bisa mencatat ini." },
  "err.payment_not_found": { en: "That payment no longer exists.", id: "Pembayaran itu sudah tidak ada." },
  "err.payment_is_transfer": { en: "Undo it on the transfer instead.", id: "Batalkan lewat transfernya." },
  "err.transfer_not_found": { en: "That transfer no longer exists.", id: "Transfer itu sudah tidak ada." },
  "err.already_paid": { en: "Already marked as paid.", id: "Sudah ditandai lunas." },
  "err.group_settled_rates": { en: "Rates are locked while settled.", id: "Kurs terkunci selama sudah diselesaikan." },
  "err.bill_rows_mode": { en: "This bill does not match its split mode.", id: "Tagihan ini tidak sesuai dengan cara pembagiannya." },
  "err.bill_unbalanced": { en: "This bill does not add up.", id: "Tagihan ini tidak pas jumlahnya." },
  "err.one_off_single_bill": { en: "A one-off holds one bill. Start a trip for more.", id: "Patungan sekali bayar hanya berisi satu tagihan. Buat perjalanan untuk lebih banyak." },
  "err.ai_limit": { en: "Daily reading limit reached. Use the form.", id: "Batas baca harian tercapai. Pakai formulir." },
  "err.ai_failed": { en: "Could not read that. Try again or use the form.", id: "Tidak bisa dibaca. Coba lagi atau pakai formulir." },
  "err.ai_unavailable": { en: "Reading is not available right now. Use the form.", id: "Fitur baca sedang tidak tersedia. Pakai formulir." },
  "err.image_invalid": { en: "Choose a JPG, PNG or WebP photo under 10 MB.", id: "Pilih foto JPG, PNG, atau WebP di bawah 10 MB." },
  "err.telegram_unavailable": { en: "Telegram is not set up on this server.", id: "Telegram belum diatur di server ini." },
  "err.draft_not_found": { en: "That draft expired. Send it again.", id: "Draf itu sudah kedaluwarsa. Kirim ulang." },
  "err.google_failed": { en: "Google sign-in did not complete. Try again.", id: "Masuk dengan Google gagal. Coba lagi." },
  "err.google_unavailable": { en: "Google sign-in is not set up here.", id: "Masuk dengan Google belum diatur di sini." },
  "err.report_invalid": { en: "Pick a report.", id: "Pilih laporan." },

  // ── admin console (the page itself is English only; errors reach it through err.*) ──
  "err.admin_unconfigured": { en: "Admin is off. Set ADMIN_PASSWORD on the server.", id: "Admin nonaktif. Atur ADMIN_PASSWORD di server." },
  "err.admin_login_required": { en: "Admin sign-in needed.", id: "Perlu masuk sebagai admin." },
  "err.admin_login_failed": { en: "Wrong admin password.", id: "Kata sandi admin salah." },
  "err.admin_user_missing": { en: "That user no longer exists.", id: "Pengguna itu sudah tidak ada." },
  "err.admin_confirm_mismatch": { en: "Type the username exactly to confirm.", id: "Ketik nama pengguna persis untuk konfirmasi." },
  "err.admin_delete_blocked": {
    en: "Nobody can take over these splits: {groups}. Delete refused.",
    id: "Tidak ada yang bisa mengambil alih patungan ini: {groups}. Penghapusan ditolak.",
  },
  "err.admin_no_base_url": { en: "Set PUBLIC_BASE_URL on the server first.", id: "Atur PUBLIC_BASE_URL di server dulu." },
  "tg.admin_pw_reset": {
    en: "An admin reset your Split Bill password.\nTemporary password: <code>{password}</code>\nSign in, then change it in Settings.",
    id: "Admin mengatur ulang kata sandi Split Bill kamu.\nKata sandi sementara: <code>{password}</code>\nMasuk, lalu ganti di Pengaturan.",
  },
};

/** Translate, with {name} placeholders filled from `params`. */
export function t(key: string, lang: string = DEFAULT_LANG, params: Record<string, string | number> = {}): string {
  const e = STRINGS[key];
  let s = e ? e[normalizeLang(lang)] || e.en : key;
  for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

/** Positional {0}/{1} form, matching the browser's t(key, a, b). */
export function tf(key: string, lang: string, ...subs: (string | number)[]): string {
  let s = t(key, lang);
  subs.forEach((v, i) => (s = s.split(`{${i}}`).join(String(v))));
  return s;
}

/** Both languages, flattened, for the static browser bundle. */
export function allBundles(): Record<Lang, Record<string, string>> {
  const en: Record<string, string> = {};
  const id: Record<string, string> = {};
  for (const [k, v] of Object.entries(STRINGS)) {
    en[k] = v.en;
    id[k] = v.id;
  }
  return { en, id };
}
